# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DependencyInjectionDemos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DependencyInjectionDemos
  pod 'Swinject', '~> 2.0.0'
  pod 'SwinjectStoryboard', '~> 1.0.0'

end
